name = "ReadLIBSVM"
uuid = "472a48ec-b7f1-4628-bb5d-b49bc9312f54"
authors = ["jeremie.desgagne.bouchard <jeremie.desgagne.bouchard@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
docs = ["Documenter"]
test = ["Test", "Downloads"]
